CREATE TABLE IF NOT EXISTS bookmark_list(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL ,
    url_address TEXT NOT NULL,
    bookmark_description TEXT , 
    rating INTEGER  DEFAULT 3 CHECK (rating >= 0 AND rating < 6) NOT NULL 
);